# .github/workflows/manual_tests.yml
# Manual workflow should have option to run full set of test or test case 5 and 6 from Problem #1.

name: Manual Test Runner

on:
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Select which tests to run'
        required: true
        default: 'full'
        type: choice
        options:
          - full       # Run all tests
          - test_5_6   # Run only test case 5 and 6 from Problem#1
jobs:
  run-tests:

    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      deployments: write
      actions: write
      checks: write
    # runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    # Step specific to Ubuntu
    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Check Chrome Version
      run: |
        google-chrome --version

    - name: Set up ChromeDriver
      run: |
        set -e # Exit immediately if a command exits with a non-zero status
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        echo "Chrome version detected: $CHROME_VERSION"

        # Download the corresponding version of ChromeDriver
        wget -q "https://chromedriver.storage.googleapis.com/${CHROME_VERSION}/chromedriver_linux64.zip"
        
        # Check if the download was successful
        if [[ $? -ne 0 ]]; then
          echo "Failed to download ChromeDriver for version $CHROME_VERSION"
          exit 1
        fi

        unzip chromedriver_linux64.zip
        
        # Move and set permissions for ChromeDriver
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Check ChromeDriver Installation
      run: |
        chromedriver --version

    - name: Set up Python 
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.9"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

     
          
    - name: Run Test Suite
      run: |
        python -m tests.test_google_finance --test-suite ${{ github.event.inputs.test_suite }}
      
