# .github/workflows/nightly_tests.yml
name: Nightly Test Runner

on:
  schedule:
    # Runs at 0 AM UTC every night;
    - cron: '0 0 * * *'

jobs:
  nightly-run:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.6"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # pip install webdriver-manager

    - name: Run Test Suite
      run: |
        python -m tests.test_google_finance
